### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by Palulukas** [Aiven-Open/prometheus-exporter-plugin-for-opensearch#213]
Hello, 

I am struggeling with getting my opensearch instances scraped.
Currently I only receive null pointer exceptions when I try to access the metrics manually. The endpoints do show as "up" in prometheus agent, though. So IP and DNS are working correctly. I configured opensearch as described in the tutorial.

Here is the job config used by the prometheus agent inside prometheus.yml: 
```
  - job_name: opensearch
    scrape_interval: 30s
    metrics_path: "/_prometheus/metrics"
    static_configs:
    - targets:
      - fqdn1:9200
      - fqdn2:9201
      - fqdn3:9200
      - ...
    basic_auth:
      username: 'user'
      password: 'pass' 
```

And the scrape result (for example fqdn1:9200) is: 

```{"error":{"root_cause":[{"type":"null_pointer_exception","reason":"Cannot invoke \"String.length()\" because \"candidate\" is null"}],"type":"null_pointer_exception","reason":"Cannot invoke \"String.length()\" because \"candidate\" is null"},"status":500}```

We use an opensearch cluster with 8 nodes, version 2.8.0, running in docker containers. 
The exporter plugin ist installed on all nodes, TLS is enabled. 
Security is also enabled and a role created -> tested with "all access".

Here is the created role: 
```
PUT _plugins/_security/api/roles/metric_reader
{
    "cluster_permissions": [
      "cluster:monitor/prometheus/metrics",
      "cluster:monitor/health",
      "cluster:monitor/state",
      "cluster:monitor/nodes/info",
      "cluster:monitor/nodes/stats"
    ],
    "index_permissions": [
      {
        "index_patterns": [
          "*"
        ],
        "dls": "",
        "fls": [],
        "masked_fields": [],
        "allowed_actions": [
          "indices:monitor/stats"
        ]
      }
    ],
    "tenant_permissions": []
}
```

and `GET_cat/plugins` shows the plugin installed on all nodes.

Is there something I need to check with my config or is there a bug in the exporter?

Regards
