### ISSUE TITLE
Can I add custom labels to metrics collection?

### ISSUE THREAD

**Issue by 10000-ki** [Aiven-Open/prometheus-exporter-plugin-for-opensearch#298]
Depending on the user-defined Grafana dashboard, various filtering may be necessary.

It would be ideal to have a structure where custom labels can be appropriately registered as needed.

For example, it would be ideal if labels could be registered in a key-value format like the following

```yml
- job_name: opensearch
  scrape_interval: 10s
  metrics_path: "/_prometheus/metrics"
  static_configs:
  - labels:
    - env: prod
    - key2: value2
    - key3: value3
    - ...
```

https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/blob/486ca19752c2016895d269da9c0f0d5fd7b5820c/src/main/java/org/compuscene/metrics/prometheus/PrometheusMetricsCollector.java#L164
